#!/usr/bin/env bash
# Download in batch exercises from a Exercism track

# @author: Daniel Souza <me@posix.dev.br>
# @license: MIT
# @usage: get-exercises.sh <lang>
# @deps: curl, jq

# Utils
# decorators
reset="\e[0;0m"
strong="\e[1;39m"
blue="\e[1;34m"
# red="\e[1;31m"
yellow="\e[1;33m"
green="\e[1;32m"

# Main
lang="$1"
url="https://exercism.org/api/v2/tracks/${lang}/exercises"
token=""
source ".env"  # source token from env

echo -e "${strong}${yellow}Getting list of exercises\t${reset}\n\n"

exercises=$(
  curl -H "Authorization: Bearer ${token}" -S "$url" |
  jq '.[] | .[] | select(.is_unlocked == true) | .slug' |
  sed 's/"//g'
)

n=$(wc -l <<< "$exercises")
i=0

mkdir -p "${lang}"
pushd "${lang}" &>/dev/null || exit

echo -e "${strong}${yellow}\nDownloading ${n} exercises...${reset}\n"
while read -r exercise; do
  i=$(( i + 1))

  if [ -d "${exercise}" ]; then
    echo -e "${strong}\n${i}. ${blue}${exercise}... ${yellow}NOOP${reset}"

  else
    echo -e "${strong}\n${i}. ${blue}${exercise}... ${green}GET${reset}"
    exercism download --exercise="${exercise}" --track="${lang}"
  fi
done <<< "$exercises"
popd &>/dev/null || exit

echo -e "${strong}${green}\nAll done!${reset}\n"
